### ISSUE TITLE
Provide a way to inject npm/yarn

### ISSUE THREAD

**Issue by andreicek** [webpack-contrib/webpack-canary#21]
This way we have control over which version/custom build of a package manager is used (e.g. yarn). We should also have sane defaults (use npm).

**Comment by DarkoKukovec** [comment]
We need to support three commands:
* Install modules: `npm install moduleA moduleB`
* Install module dependencies (dev): `npm install`
* Link package: `npm link moduleB` - will probably need it for #24 

Exposed config:
* npm or yarn (and which version)
  * examples:
    * `"npm"` - uses the system npm
    * `"npm@4"` - installs `npm@4` locally and uses it
    * `"yarn"` - uses the system yarn
  * how to install yarn?
* custom package managers?
  * Define a list of commands?

**Comment by andreicek** [comment]
I gave a possible solution for this in #26. What do you think?

**Comment by DarkoKukovec** [comment]
I think we should go with the following options for the initial release: `"npm"`, `"yarn"`, and we'll see if there will be any need for `"npm@version"` or any other options.
